"""create the db tables

Revision ID: a584a869cb40
Revises: 
Create Date: 2021-03-25 12:17:38.543899

"""
import json

from alembic import op
import sqlalchemy as sa

from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

# revision identifiers, used by Alembic.
revision = 'a584a869cb40'
down_revision = None
branch_labels = None
depends_on = None

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('products')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    products_table = op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('picture', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with open("data/products.json") as fd:
        op.bulk_insert(products_table, json.load(fd)['products'])

    customers_table = op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=64), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('zip', sa.VARCHAR(length=32), nullable=True),
    sa.Column('country', sa.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with open("data/customers.json") as fd:
        op.bulk_insert(customers_table, json.load(fd))

    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    db.create_all()
    # ### end Alembic commands ###
